version: "3.9"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev_stage
      args:
        NODE_ENV: dev
    ports:
      - "3030:80"
    env_file:
      - ./client/.env.dev
    environment:
      NODE_ENV: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["sh", "-c", "PORT=80 npm start"]
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev_stage
      args:
        NODE_ENV: dev
    ports:
      - "5050:5050"
    env_file:
      - ./server/.env.dev
    environment:
      NODE_ENV: dev
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

